#!/usr/bin/python3
# A program for trimal'ing all files that contain protein sequences of single-copy orthologs.
# USAGE: ./trimal4Orthofiles_TA.py
# Author: Taruna Aggarwal
# Affiliation: University of New Hampshire, Durham, NH, USA
# Date: 01/27/2016
# Purpose is to trim sites in protein alignment files generated by Orthofinder.

# This scripts assumes the alignment files contain single-copy orthologs.

import os
import subprocess
import argparse


parser = argparse.ArgumentParser(description="This script runs trimal for files in a directory.")
parser.add_argument('--root', help="PATH to the directory containing orthogroup files.", required=True)
parser.add_argument('--trimal_dir', help="PATH to the directory for trimmed orthogroup files.", required=True)
args = parser.parse_args()


def runtrimal(input_file, output_file):
    trimal_command = "trimal -in {0} -out {1} -gappyout".format(input_file, output_file)
    subprocess.call(trimal_command, shell=True)

Orig_file_dir = args.root
trimal_file_dir = args.trimal_dir

try:
    os.makedirs(trimal_file_dir)
except FileExistsError as e:
    pass

for currentFile in os.listdir(args.root):
    if currentFile.endswith(".fa"):
        trimmed_output = runtrimal(args.root + "/" + currentFile, args.trimal_dir + "/" +  currentFile[:-3]+"_trimmed.fa")
