#!/usr/bin/python3
# A program for finding dna fasta files that correspond to the protein fasta files containing single-copy orthologs
# USAGE: ./proteinOrthos2dnaOrthos_TA.py
# Author: Taruna Aggarwal
# Affiliation: University of New Hampshire, Durham, NH, USA
# Date: 01/20/2016
# Purpose is parse through a protein orthogroup fasta file generated by Orthofinder; identify parts of the headers
# that contain original protein file names + some identifier for the protein file unique to the header; look for the
# identifier in the CDS file header; write the header + file name + species name and its corresponding sequence to a
# new file

import os
import sys

# create an empty list that will contain all the identifiers from pep file headers that correspond to the cds file headers
# create an empty dictionary that will keep the file names as key and the identifiers as values
cds_names = []
cds_dict = {}
# CHANGE THIS LINE
for currentFile in os.listdir("/home/mcclintock/ta2007/myscripts/orthogroupScripts/orthogroups_files/"):
    # print(currentFile)
    # MAKE SURE THE ORTHOGROUP FILES END WITH ".fa"
    if currentFile.endswith(".fa"):
        # CHANGE THIS LINE
        working_file = open("/home/mcclintock/ta2007/myscripts/orthogroupScripts/orthogroups_files/" + currentFile, "r")
        for currentLine in working_file:
            currentLine = currentLine.rstrip()
            if currentLine.startswith(">"):
                # find pattern
                try:
                    default_name = currentLine.split('TARUNA_')[1]
                    species_name = currentLine.split('TARUNA_')[0]
                except IndexError:
                    pass
                # print(default_name)
                # THESE PATTERNS MIGHT BE DIFFERENT FOR THE SPECIES YOUR ARE USING
                cds_names.append((species_name, default_name))
                cds_names.append((species_name, default_name.replace("P", "T")))
                if "|" in default_name:
                    modified_cds_name = default_name.split("|")
                    cds_names.append((species_name, modified_cds_name[-1]))
        # print(currentFile)
        # print(cds_names)
        # print(len(cds_names))
        # print(set(cds_names))
        # print(len(set(cds_names)))
        if currentFile not in cds_dict:
            key = currentFile
            cds_dict[key] = list(set(cds_names))


# for filename, value in cds_dict.items():
#     print("{0}\n{1}\n{2}".format(filename, value, len(id)))
# exit()

# CONCATENATE ALL THE CDS FILES
# CHANGE THIS LINE
combined_cds_file = open("/home/mcclintock/ta2007/myscripts/orthogroupScripts/orthogroups_files/cds_files/ALLcds.fa", "r")
# print("The length of dict is: {}".format(len(cds_dict)))
for filename, value in cds_dict.items():
    new_file = open("CDS_"+filename, "w")
    flag = False
    for line in combined_cds_file:
        line = line.rstrip()
        if line.startswith(">"):
            for index in value:
                if index[1] in line:
                    new_file.write("{0}_{1}_{2}\n".format(index[0], filename, line[1:]))
                    flag = True
                    break
                else:
                    flag = False
        elif flag:
            new_file.write("{0}\n".format(line))
    combined_cds_file.seek(0)

working_file.close()
combined_cds_file.close()
new_file.close()
